/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devnan_jnidemo_JNI */


#ifndef _Included_com_devnan_jnidemo_JNI
#define _Included_com_devnan_jnidemo_JNI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL stringFromJNI (
        JNIEnv *env,
        jobject /* this */);

const char *className = "com/devnan/ndk/MainActivity";

const JNINativeMethod gMethods[] = {
        /* name, signature, funcPtr */
        {"stringFromJNI", "()Ljava/lang/String;", (void *) stringFromJNI},
};

#ifdef __cplusplus
}
#endif
#endif
